# Generated by Django 3.2 on 2025-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('lokasi', models.CharField(max_length=50)),
                ('tanggal_masuk', models.DateField()),
            ],
        ),
    ]
