# Generated by Django 3.2 on 2025-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
