# Generated by Django 3.2 on 2025-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_pemasok'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='pemasok',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
